//! Config file generation for Tell
//!
//! Generates a minimal TOML config file with ClickHouse sink configured.

/// Generate a minimal Tell config file for the given workspace
pub fn generate_config(
    workspace: &str,
    clickhouse_url: &str,
    collector_password: &str,
    dashboard_password: &str,
) -> String {
    // Extract host from URL (remove http:// prefix if present)
    let host = clickhouse_url
        .strip_prefix("http://")
        .or_else(|| clickhouse_url.strip_prefix("https://"))
        .unwrap_or(clickhouse_url);

    format!(
        r#"# Tell - {workspace}
# Generated by: tell clickhouse init {workspace}
# See configs/example.toml for all options

[[sources.tcp]]
port = 50000

[sinks.clickhouse]
host = "{host}"
database = "{workspace}"
username = "{workspace}_collector"
password = "{collector_password}"

[routing]
default = ["clickhouse"]

# Dashboard/API credentials (read-only)
# Used by: tell api, tell query, tell metrics
[clickhouse]
host = "{host}"
database = "{workspace}"
username = "{workspace}_dashboard"
password = "{dashboard_password}"
"#,
        workspace = workspace,
        host = host,
        collector_password = collector_password,
        dashboard_password = dashboard_password,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_config() {
        let config = generate_config(
            "acme",
            "http://localhost:8123",
            "collector_pw",
            "dashboard_pw",
        );

        assert!(config.contains("database = \"acme\""));
        assert!(config.contains("username = \"acme_collector\""));
        assert!(config.contains("password = \"collector_pw\""));
        assert!(config.contains("username = \"acme_dashboard\""));
        assert!(config.contains("password = \"dashboard_pw\""));
        assert!(config.contains("host = \"localhost:8123\""));
        assert!(config.contains("default = [\"clickhouse\"]"));
        // Should NOT contain verbose settings
        assert!(!config.contains("batch_size"));
        assert!(!config.contains("[tap]"));
        assert!(!config.contains("[metrics]"));
    }

    #[test]
    fn test_strips_http_prefix() {
        let config = generate_config("test", "http://ch.example.com:8123", "c", "d");
        assert!(config.contains("host = \"ch.example.com:8123\""));

        let config = generate_config("test", "https://secure.example.com:8443", "c", "d");
        assert!(config.contains("host = \"secure.example.com:8443\""));
    }
}
